### ISSUE TITLE
Ublock origin stops extension from working

### ISSUE THREAD

**Issue by Frozen-Fang** [KemonoExtended/Kemono-Extended#1]
Is there something I can whitelist to keep this working with ublock origin?

**Comment by KemonoExtended** [comment]
Can you provide any mode information? 
What exactly is happening/not working?
Which site is affected?
Did you enable the respective setting?
What device are you using.

**Comment by Frozen-Fang** [comment]
Sorry this took so long didn't get a notification for this for some reason,

The whole extension doesn't work when unlock origin is activated like all the features of your addon I would need to turn off ublock origin for it to work at all

**Comment by KemonoExtended** [comment]
I've made some changes that increase reliability. Let me know if your issue is still occurring.

**Comment by KemonoExtended** [comment]
You might need to manually check for addon updates by going to about:addons, clicking on the gear icon and choosing "Check for updates".

**Comment by KemonoExtended** [comment]
Good idea. I've implemented it.
