### ISSUE TITLE
New update broke extension

### ISSUE THREAD

**Issue by Frozen-Fang** [KemonoExtended/Kemono-Extended#2]
Was working from when you fixed it last update now it doesn't work at all not showing normal thumbnails anymore 

Edit: some aspects still work like downloader and swipe and read

thumbnails broke again no text in thumb for text thumbnails

no images for image thumbnails

no video thumbnails in coomer.su

**Comment by KemonoExtended** [comment]
Kemono and Coomer recently switched to React. This means that the usual triggers this extension uses dont work. I am working on an update.

**Comment by KemonoExtended** [comment]
The changes to the websites were rolled back. Right now the addon works again but i would assume they are working on switching back to React.
