### ISSUE TITLE
Make restore post thumbnails work when searching a users page

### ISSUE THREAD

**Issue by Frozen-Fang** [KemonoExtended/Kemono-Extended#3]
Noticed that restore post thumbnails doesn't work when you search on a users page, all other functions work but it's only when you search using the search bar from a user page that it doesn't restore post thumbnails on the results screen this applies to kemono & coomer as well

Edit: seems to also not be working on any page but the first page on user

**Comment by KemonoExtended** [comment]
My bad for ignoring this. This issue will be resolved in the next release. This release has been delayed because the website was updated. That update broke a lot of the ways that the extension interacted with the website. It has been a challenge to fix, but it could be ready in a few days.

**Comment by KemonoExtended** [comment]
This is fixed in the new version.
